replicaCount: 2
maxUnavailable: 1

app:
  image:
    repository: danonthemoon/tm-medals-app
    pullPolicy: Always
    tag: latest
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 80
  securityContext: {}

api:
  image:
    repository: danonthemoon/tm-medals-api
    pullPolicy: Always
    tag: latest
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8081
  securityContext: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  hosts:
    - host: tm-medals.danonthemoon.dev
    - host: www.tm-medals.danonthemoon.dev
  tls:
    - hosts:
        - tm-medals.danonthemoon.dev
        - www.tm-medals.danonthemoon.dev
      secretName: tm-medals-tls
  directs: []

nodeSelector: {}
tolerations: []
affinity: {}
