apiVersion: v1
kind: Service
metadata:
  name: {{ include "tm-api.fullname" . }}
  labels: {{ include "tm-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: api-http
      protocol: TCP
      name: api-http
  selector: {{ include "tm-api.selectorLabels" . | nindent 4 }}
