apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "holydynasty-events.fullname" . }}
  labels:
    {{- include "holydynasty-events.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "holydynasty-events.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "holydynasty-events.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "holydynasty-events.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: app-http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: app-http
          readinessProbe:
            httpGet:
              path: /ready
              port: app-http
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
        - name: api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: DATABASE_CONNSTR
              valueFrom:
                secretKeyRef:
                  name: holydynasty-events-api
                  key: DATABASE_CONNSTR
            - name: ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: holydynasty-events-api
                  key: ADMIN_KEY
            - name: DATABASE_SSL
              value: "true"
            - name: HOST
              value: "0.0.0.0"
            - name: TMIO_URL
              value: {{ .Values.tmioUrl }}
            - name: DISCORD_INVITE_URL
              value: {{ .Values.discordInviteUrl }}
            - name: TMPDIR
              value: /tmp
          ports:
            - name: api-http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: api-http
          readinessProbe:
            httpGet:
              path: /ready
              port: api-http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
