apiVersion: v1
kind: Service
metadata:
  name: {{ include "holydynasty-events.fullname" . }}
  labels: {{- include "holydynasty-events.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: app-http
      protocol: TCP
      name: app-http
    - port: {{ .Values.api.service.port }}
      targetPort: api-http
      protocol: TCP
      name: api-http
  selector: {{- include "holydynasty-events.selectorLabels" . | nindent 4 }}
