replicaCount: 1
maxUnavailable: 1

app:
  image:
    repository: danonthemoon/holydynasty-events-app
    pullPolicy: Always
    tag: latest
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
  service:
    port: 80
  securityContext: {}

api:
  image:
    repository: danonthemoon/holydynasty-events-api
    pullPolicy: Always
    tag: latest
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8081
  securityContext: {}

tmioUrl: http://tmiosim:8100
discordInviteUrl: https://discord.gg/yR5EtqAWW7

imagePullSecrets:
  - name: danonthemoon-ips
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

service:
  type: ClusterIP

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
  directs: []

nodeSelector: {}
tolerations: []
affinity: {}
