import { HttpClient } from '@angular/common/http'
import { Injectable } from '@angular/core'
import { TeamResponse } from 'src/domain/team'
import { TeamRole } from 'src/domain/team'
import { Observable, of } from 'rxjs'

@Injectable({ providedIn: 'root' })
export class TeamService {
  constructor(private _: HttpClient) {}

  getAll(): Observable<TeamResponse> {
    return of({
      teams: [
        {
          name: 'Speed Demons',
          description: 'A team of the fastest players.',
          visible: true,
          dateCreated: new Date('2025-01-01'),
          dateModified: new Date('2025-05-01'),
          players: [
            {
              accountId: '12345',
              name: 'PlayerOne',
              role: TeamRole.PLAYER,
              image: 'assets/images/player1.jpg',
              twitch: '',
              discord: 'player1#1234',
            },
            {
              accountId: '67890',
              name: 'PlayerTwo',
              role: TeamRole.CAPTAIN,
              image: '',
              twitch: 'player2',
              discord: '',
            },
            { accountId: '11111', name: 'PlayerEleven', role: TeamRole.PLAYER, image: '', twitch: '', discord: '' },
            {
              accountId: '22222',
              name: 'PlayerTwelve',
              role: TeamRole.PLAYER,
              image: 'assets/images/player12.jpg',
              twitch: '',
              discord: '',
            },
            {
              accountId: '33333',
              name: 'PlayerThirteen',
              role: TeamRole.PLAYER,
              image: '',
              twitch: 'player13',
              discord: '',
            },
            {
              accountId: '44444',
              name: 'PlayerFourteen',
              role: TeamRole.PLAYER,
              image: '',
              twitch: '',
              discord: 'player14#5678',
            },
          ],
          sortOrder: 1,
        },
        {
          name: 'Turbo Titans',
          description: 'Masters of turbo tracks.',
          visible: true,
          dateCreated: new Date('2025-01-01'),
          dateModified: new Date('2025-05-01'),
          players: [
            {
              accountId: '11223',
              name: 'PlayerThree',
              role: TeamRole.PLAYER,
              image: 'assets/images/player3.jpg',
              twitch: 'player3',
              discord: '',
            },
            {
              accountId: '44556',
              name: 'PlayerFour',
              role: TeamRole.COACH,
              image: '',
              twitch: '',
              discord: 'player4#9101',
            },
            { accountId: '55555', name: 'PlayerFifteen', role: TeamRole.PLAYER, image: '', twitch: '', discord: '' },
            {
              accountId: '66666',
              name: 'PlayerSixteen',
              role: TeamRole.PLAYER,
              image: 'assets/images/player16.jpg',
              twitch: '',
              discord: '',
            },
            {
              accountId: '77777',
              name: 'PlayerSeventeen',
              role: TeamRole.PLAYER,
              image: '',
              twitch: '',
              discord: 'player17#1122',
            },
            {
              accountId: '88888',
              name: 'PlayerEighteen',
              role: TeamRole.PLAYER,
              image: '',
              twitch: 'player18',
              discord: '',
            },
          ],
          sortOrder: 2,
        },
        {
          name: 'Nitro Ninjas',
          description: 'Stealthy and fast.',
          visible: true,
          dateCreated: new Date('2025-01-01'),
          dateModified: new Date('2025-05-01'),
          players: [
            {
              accountId: '77889',
              name: 'PlayerFive',
              role: TeamRole.PLAYER,
              image: '',
              twitch: '',
              discord: 'player5#3344',
            },
            {
              accountId: '99001',
              name: 'PlayerSix',
              role: TeamRole.SUBSTITUTE,
              image: 'assets/images/player6.jpg',
              twitch: 'player6',
              discord: '',
            },
            { accountId: '99999', name: 'PlayerNineteen', role: TeamRole.PLAYER, image: '', twitch: '', discord: '' },
            {
              accountId: '10101',
              name: 'PlayerTwenty',
              role: TeamRole.PLAYER,
              image: '',
              twitch: 'player20',
              discord: '',
            },
            {
              accountId: '20202',
              name: 'PlayerTwentyOne',
              role: TeamRole.PLAYER,
              image: 'assets/images/player21.jpg',
              twitch: '',
              discord: '',
            },
            {
              accountId: '30303',
              name: 'PlayerTwentyTwo',
              role: TeamRole.PLAYER,
              image: '',
              twitch: '',
              discord: 'player22#5566',
            },
          ],
          sortOrder: 3,
        },
        {
          name: 'Velocity Vipers',
          description: 'Striking with speed.',
          visible: true,
          dateCreated: new Date('2025-01-01'),
          dateModified: new Date('2025-05-01'),
          players: [
            {
              accountId: '22334',
              name: 'PlayerSeven',
              role: TeamRole.PLAYER,
              image: '',
              twitch: 'player7',
              discord: '',
            },
            {
              accountId: '55667',
              name: 'PlayerEight',
              role: TeamRole.CASTER,
              image: 'assets/images/player8.jpg',
              twitch: '',
              discord: 'player8#7788',
            },
            {
              accountId: '40404',
              name: 'PlayerTwentyThree',
              role: TeamRole.PLAYER,
              image: '',
              twitch: '',
              discord: '',
            },
            {
              accountId: '50505',
              name: 'PlayerTwentyFour',
              role: TeamRole.PLAYER,
              image: '',
              twitch: 'player24',
              discord: '',
            },
            {
              accountId: '60606',
              name: 'PlayerTwentyFive',
              role: TeamRole.PLAYER,
              image: 'assets/images/player25.jpg',
              twitch: '',
              discord: '',
            },
            {
              accountId: '70707',
              name: 'PlayerTwentySix',
              role: TeamRole.PLAYER,
              image: '',
              twitch: '',
              discord: 'player26#9900',
            },
          ],
          sortOrder: 4,
        },
        {
          name: 'Rocket Racers',
          description: 'Blazing through the tracks.',
          visible: true,
          dateCreated: new Date('2025-01-01'),
          dateModified: new Date('2025-05-01'),
          players: [
            {
              accountId: '33445',
              name: 'PlayerNine',
              role: TeamRole.PLAYER,
              image: '',
              twitch: '',
              discord: 'player9#2233',
            },
            {
              accountId: '66778',
              name: 'PlayerTen',
              role: TeamRole.OWNER,
              image: 'assets/images/player10.jpg',
              twitch: 'player10',
              discord: '',
            },
            {
              accountId: '80808',
              name: 'PlayerTwentySeven',
              role: TeamRole.PLAYER,
              image: '',
              twitch: '',
              discord: '',
            },
            {
              accountId: '90909',
              name: 'PlayerTwentyEight',
              role: TeamRole.PLAYER,
              image: '',
              twitch: 'player28',
              discord: '',
            },
            {
              accountId: '10110',
              name: 'PlayerTwentyNine',
              role: TeamRole.PLAYER,
              image: 'assets/images/player29.jpg',
              twitch: '',
              discord: '',
            },
            {
              accountId: '11111',
              name: 'PlayerThirty',
              role: TeamRole.PLAYER,
              image: '',
              twitch: '',
              discord: 'player30#4455',
            },
          ],
          sortOrder: 5,
        },
      ],
    })
  }
}
