name: HDs TM Events
on:
  push:
    paths:
      - .github/workflows/hds-tm-events.yaml
      - apis/hds-tm-events/**
      - apps/hds-tm-events/**
      - charts/holydynasty-events/**
      - dbs/hsdtmevents/**
      - environment/prod/holydynasty-events.values.yaml
      # - plugins/hds-bounty/**
      # - sims/**
      # - tests/hds-tm-events/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/hds-tm-events
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun test
  deploy:
    runs-on: ubuntu-latest
    needs: [api]
    if: ${{ (github.head_ref || github.ref_name) == 'main' }}
    environment: holydynasty.events
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: apis/hds-tm-events
          push: true
          tags: danonthemoon/holydynasty-events-api:latest
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: apps/hds-tm-events
          push: true
          tags: danonthemoon/holydynasty-events-app:latest
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Helm Upgrade
        shell: bash
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 240 ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
          helm dependency update ./charts/holydynasty-events
          helm -n holydynasty-events upgrade --install --wait --timeout 60s --atomic holydynasty-events ./charts/holydynasty-events/ -f ./environment/prod/holydynasty-events.values.yaml
