name: TM Api
on:
  push:
    paths:
      - .github/workflows/tm-api.yaml
      - apis/tm-api/**
      - charts/tm-api/**
      - dbs/tmapi/**
      - sims/**
      - tests/tm-api/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/tm-api
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun test
  deploy:
    runs-on: ubuntu-latest
    needs: [api]
    if: ${{ (github.head_ref || github.ref_name) == 'main' }}
    environment: tm-api.danonthemoon.dev
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: apis/tm-api
          push: true
          tags: danonthemoon/tm-api:latest
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Helm Upgrade
        shell: bash
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 240 ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
          helm dependency update ./charts/tm-api
          helm -n tm-api upgrade --install --wait --timeout 180s --atomic tm-api ./charts/tm-api/
